# Generated by Django 5.2.8 on 2025-12-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='bibliografia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
