# Generated by Django 5.2.8 on 2025-12-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_autor_bibliografia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'permissions': (('Ver_prestamos', 'Puede ver prestaamos'), ('gestionar_prestamos', 'Puede gestionar_prestamos'))},
        ),
    ]
