# Generated by Django 5.2.8 on 2025-12-24 00:31

import django.db.models.deletion
import gestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_editorial_alter_autor_options_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioBiblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[gestion.models.validar_cedula_ecuatoriana])),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('externo', 'Externo')], default='externo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='usuario_biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='gestion.usuariobiblioteca'),
        ),
    ]
