# Generated by Django 5.2.8 on 2025-12-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_usuariobiblioteca_remove_prestamo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_max',
            field=models.DateField(blank=True, null=True),
        ),
    ]
