# Generated by Django 5.2.8 on 2025-12-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_prestamo_fecha_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='multa',
            name='tipo',
            field=models.CharField(choices=[('r', 'Retraso'), ('p', 'Pérdida'), ('d', 'Deterioro')], max_length=1),
        ),
    ]
