# Generated by Django 5.2.8 on 2025-12-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_multa_monto_alter_multa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='estado_libro',
            field=models.CharField(blank=True, choices=[('bueno', 'Buen Estado'), ('danado', 'Dañado'), ('perdido', 'Perdido')], default='bueno', max_length=10),
        ),
    ]
